dist: xenial

sudo: required

language: cpp

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
  - curl -s -L https://nvidia.github.io/nvidia-docker/$(. /etc/os-release;echo $ID$VERSION_ID)/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
  - sudo apt-key fingerprint 0EBFCD88
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install -y docker-ce
  - sudo apt-get install -y nvidia-docker2
  - sudo pkill -SIGHUP dockerd
  - docker build --build-arg COMMIT=$TRAVIS_COMMIT -t simtrack .

script:
  - docker run --rm simtrack /bin/bash -c "source /opt/ros/kinetic/setup.sh && catkin_make -DCMAKE_BUILD_TYPE=\"Release\""

